name: Auto Download APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create folder and Download APK from Private Repo
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: |
          mkdir -p download
          
          # নতুন ভার্সন v1.5.5 ডাউনলোড করার কমান্ড
          gh release download v1.5.5 --repo jubairbro/Muhasabah-app --pattern "Muhasabah-v1.5.5.apk" --dir download/

      - name: Commit and Push to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # নতুন ফাইলটি অ্যাড করা হচ্ছে
          git add download/Muhasabah-v1.5.5.apk
          
          # কমিট মেসেজ আপডেট
          git commit -m "Auto added Muhasabah v1.5.5 APK" || echo "No new file to commit"
          
          git push
