name: Auto Download Multiple APKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create folders and Download APKs from Other Account
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }} # এখানে আপনার নতুন টোকেনটি কাজ করবে
        run: |
          # দুটি আলাদা ফোল্ডার তৈরি করা হচ্ছে
          mkdir -p download/debug
          mkdir -p download/release
          
          # ১. Debug ভার্সন ডাউনলোড (JubairZ অ্যাকাউন্ট থেকে)
          gh release download v1.7.0 --repo JubairZ/Muhasabah-app --pattern "Muhasabah-DEBUG-v1.7.0.apk" --dir download/debug/
          
          # ২. Release ভার্সন ডাউনলোড (JubairZ অ্যাকাউন্ট থেকে)
          gh release download v1.7.0 --repo JubairZ/Muhasabah-app --pattern "Muhasabah-v1.7.0.apk" --dir download/release/

      - name: Commit and Push to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # নতুন দুটি ফাইলই গিট-এ অ্যাড করা হচ্ছে
          git add download/debug/Muhasabah-DEBUG-v1.7.0.apk
          git add download/release/Muhasabah-v1.7.0.apk
          
          git commit -m "Added v1.7.0 Debug and Release APKs from JubairZ repo" || echo "No new files to commit"
          git push
